### ISSUE TITLE
Simplify3D support

### ISSUE THREAD

**Issue by mrhanman** [tjjfvi/OctoPrint-SlicerSettingsParser#2]
Gcode from Simplify3D only show Z height changes for each layer, and not the actual settings themselves.  Is it possible to get support for S3D gcode, please?

**Comment by tjjfvi** [comment]
Currently, this only supports Slic3r, but I will look into supporting Simplify3D.

*Note: I transfered this issue to OctoPrint-SlicerSettingsParser because the issue is not with the tab plugin.*

**Comment by tjjfvi** [comment]
@mrhanman: Could you send me a gcode file of yours from Simplify3D so I can see if/how it can be supported?

**Comment by tjjfvi** [comment]
Nevermind; got one. Feel free to send another though.

**Comment by tjjfvi** [comment]
@mrhanman: Use this sed command:
```
/^;   .*,.*$/!d ; s/^;   \([^,]*\),\(.*\)/\1=\2/
````

**Comment by mrhanman** [comment]
That works perfectly. Thanks!

**Comment by tjjfvi** [comment]
In v2.0.0 (released 2018-01-04), Simplify3D support is included by default.
