### ISSUE TITLE
Files uploaded via Web UI aren't analyzed

### ISSUE THREAD

**Issue by 3d-gussner** [tjjfvi/OctoPrint-SlicerSettingsParser#3]
Thanks for the Plugin, maybe i am wrong but if i upload a new gcode to my Octoprint i get a
```
No Slicer Settings
(for this file)
```
message. After i go in SlicerSettingsParser and hit the `Analyze all files` the info is shown next time.

Is there a way that it automatically works after an upload or do i have to wait a bit?

**Comment by tjjfvi** [comment]
@3d-gussner, @raulttro: What slicer are you using?
@ghawk1ns: Yes, Cura isn't currently supported; see #1 for more details and updates.

*Note: I transferred the issue to OctoPrint-SlicerSettingsParser because it is not an issue with the tab plugin.*

**Comment by tjjfvi** [comment]
@3d-gussner: Sorry, I should've read your ticket more closely. Yes, I see this is a bug; I'll look into it soon.

**Comment by tjjfvi** [comment]
I think that it is fixed in v2.0.0, @3d-gussner, could you confirm? You may have to wait a couple seconds before selecting the file.

**Comment by tjjfvi** [comment]
I’m closing this for now; feel free to reopen if the issue shows up again.

**Comment by Rednax74** [comment]
Hello, I have the issue that files are not automatically parsed after upload. If I triggered it via the settings analyse all this works fine.
