### ISSUE TITLE
[Feature] Cura support

### ISSUE THREAD

**Issue by varazir** [tjjfvi/OctoPrint-SlicerSettingsParser#6]
**Please support:** Cura
I know there are previous post about adding settings to your start/exit code. 
It's it better to get it right with the correct regexp? 

**Sample gcode**: 
https://gist.github.com/varazir/4a290275cc2b8da43feea4a9ba982493

I'm trying to understand how the parser works, I used this site to test my regexp ( and get help) https://regex101.com

If I understand correct n\ is replaced with a New line before the file get parsed ? 
If  that is the case [this ]( https://regex101.com/r/aEAIv8/9 )should remove the ;SETTING_3  garbage and [this ](https://regex101.com/r/aEAIv8/8) should pick the correct values. 

If it's not the case that \n get replaced before parsing [this](https://regex101.com/r/aEAIv8/7) should get the correct values after [this ]( https://regex101.com/r/aEAIv8/9 )

I added [this ](https://regex101.com/r/aEAIv8/12) as well to get only the data that is needed.

Tested both but the SlicerSettingsTab can't find any settings. 

```
;End of Gcode[\s\S]+
\n?;SETTING_3 
(?P<key>\w+) = (?P<val>[^\\]+)
```

**Comment by tjjfvi** [comment]
@varazir: Please use the g-code script for Cura support located [here](https://csi.t6.fyi/). There are more details in the original issue (#1), but there are two core problems:
1. It only shows settings that were changed.
2. JSON cannot be parsed with regular expressions.

However, you are correct that `\\n` is equivalent to a newline in their format.
Also, SlicerSettingsTab just taps off of the settings parsed by this plugin.

If you do find a regex way to parse this, please let me know!

For now, I am closing this; feel free to follow up and/or reopen.

**Comment by varazir** [comment]
I don't want to add that amount of data in the exit/start code. If I reinstall Cura I nee dto remember to add it. 
If you look at the regexp I posted I managed to extract the values from orginal Cura settings information.

**Comment by tjjfvi** [comment]
@varazir: Relative to gcode, the script is *tiny*. However, I'll take a look at your regexes.

**Comment by tjjfvi** [comment]
@varazir: While it seems that, combined, your regexes would work, it currently only supports a single regex.

**Comment by varazir** [comment]
@tjjfvi ya need of 2 atleast. One to remove the \n?;SETTING_3  and second (?P<key>\w+) = (?P<val>[^\\]+) to get the data. The first one is just to lower the amout of data needed to process

**Comment by varazir** [comment]
@tjjfvi could you add support for more then one regexp ?

**Comment by tjjfvi** [comment]
@varazir: I'm sorry, but I'm too busy with other projects right now, but if you submit a PR, I can merge & release it.

**Comment by varazir** [comment]
@tjjfvi  I wish I could code. can take a look see if I can make heads and tail. Not it's bed code just I'm bad it :)
